services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=task_scheduler'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'  # Map container port 3306 to host port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data between container restarts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'  # Map container port 6379 to host port 6379
    volumes:
      - redis_data:/data  # Persist Redis data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  redis_data: